In [2]:
import pickle
import pandas as pd
import sys
import time
import numpy as np

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

In [15]:
with open("../../output/run_output/final_diarization_output_AVA_AVD_MY_DATASET.pckl", "rb") as fil:
    diarization_output = pickle.load(fil)
diarization_output.keys()

dict_keys(['2qQs3Y9OJX0_c_03', '7YpF6DntOYw_c_03', 'HKjR70GCRPE_c_02', 'IKdBLciu_-A_c_03', 'PmElx9ZVByw_c_02', 'StarTalk_Mars_1680_1780', 'StarTalk_Mars_2315_2376', 'StarTalk_Mars_927_1025', 'StarTalk_Questions_831_5_924'])

In [19]:
with open("../../output/video_temp/2qQs3Y9OJX0_c_03/pywork/encoding_df.pckl", "rb") as fil:
    encoding_df = pickle.load(fil)

In [21]:
encoding_df

,Frame,Track,Score,S,X,Y,Encoding
0,71,0,0.04,26.950052,358.246658,81.448732,"[-0.1546468436717987, 0.10719984024763107, 0.0..."
1,72,0,0.26,26.054571,357.858566,81.195532,"[-0.12708964943885803, 0.10166827589273453, 0...."
2,73,0,0.34,26.054571,357.588089,81.153996,"[-0.15665265917778015, 0.12456390261650085, 0...."
3,74,0,0.34,26.054571,357.366959,81.153996,"[-0.2195330709218979, 0.118991419672966, 0.077..."
4,75,0,0.30,26.054571,356.911194,81.153996,"[-0.19757080078125, 0.11144435405731201, 0.056..."
...,...,...,...,...,...,...,...
2853,7450,53,2.22,50.751091,348.179977,104.130680,"[-0.042684029787778854, 0.010113636963069439, ..."
2854,7451,53,1.60,50.847164,350.544968,105.019505,"[-0.039921943098306656, 0.012519676238298416, ..."
2855,7452,53,0.90,50.972691,352.047852,107.710133,"[-0.04156479239463806, 0.005479415878653526, 0..."
2856,7453,53,0.28,50.974880,355.329300,108.933584,"[-0.009813249111175537, -0.006327866576611996,..."
2857,7365,54,0.06,57.237251,94.713509,113.637934,"[-0.07658703625202179, 0.03663496673107147, 0...."

In [24]:
perform_clustering(encoding_df["Encoding"].to_list())

Num of clusters - 2 - 0.15556839675966846
Num of clusters - 3 - 0.2031253923389932
Num of clusters - 4 - 0.21148809192860044
Num of clusters - 5 - 0.17463314588621864
Num of clusters - 6 - 0.1760114888578479

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]

In [23]:
def perform_clustering(encoding_list, min_clusters=2, max_clusters=6, input_clusters=-1, silhouette_threshold = 0.25):

    optimal_cluster = -1
    max_silhouette = 0
    
    num_points = len(encoding_list)
    
    if input_clusters < 0:
        for num_clusters in range(min_clusters, max_clusters + 1):
            if num_clusters >= num_points:
                break
            kmeans = KMeans(n_clusters=num_clusters, random_state=42, n_init=10)
            cluster_labels = kmeans.fit_predict(encoding_list)

            silhouette_avg = silhouette_score(encoding_list, cluster_labels)
            print(f"Num of clusters - {num_clusters} - {silhouette_avg}")

            if silhouette_avg > max_silhouette:
                max_silhouette = silhouette_avg
                optimal_cluster = num_clusters
    else:
        optimal_cluster = input_clusters
        
    if max_silhouette >= silhouette_threshold:
        kmeans = KMeans(n_clusters=optimal_cluster, random_state=42, n_init=10)
        cluster_labels = kmeans.fit_predict(encoding_list)
        
    else:
        cluster_labels = [0] * len(encoding_list)

    return cluster_labels



def find_centroid(points):
    # Calculate the mean along each dimension
    centroid = np.mean(points, axis=0)
    return centroid

def mini_track_group(track_id, temp_df):
    
    centroid_list = []
    
    for cluster_num in temp_df["Track_Cluster_ID"].unique():
        centroid = find_centroid(list(temp_df[temp_df["Track_Cluster_ID"] == cluster_num]["Encoding"]))
        centroid_list.append({"Track": track_id, "Track_Cluster_ID": cluster_num, "Track_Cluster_Centroid": centroid})

    return centroid_list

In [6]:
def get_subset(df):
    
    if "Track" not in df.columns:
        print("Invalid df")
        return None
    if "Encoding" not in df.columns:
        print("Invalid df")
        return None
    
    def remove_first_two_rows(group):
        return group.iloc[2:]
    
    df_filtered = df.groupby('Track').apply(remove_first_two_rows).reset_index(drop=True)
    
    track_centroid_list = []
    df_list = []
    
    for track_id in list(df_filtered["Track"].unique()):
        temp = df_filtered[df_filtered["Track"] == track_id].copy()
        temp["Track_Cluster_ID"] = perform_clustering(list(temp["Encoding"]), max_clusters=3)
        
        track_centroid_list.extend(mini_track_group(track_id, temp))
        df_list.append(temp)
        
    return pd.concat(df_list), pd.DataFrame(track_centroid_list)

In [7]:
class TrackCluster:
    def __init__(self, track_cluster_cluster_id, track_cluster_cluster_count, track_cluster_percent):
        self.track_cluster_cluster_id = track_cluster_cluster_id
        self.track_cluster_cluster_count = track_cluster_cluster_count
        self.track_cluster_percent = track_cluster_percent

    def __lt__(self, other):
        return self.track_cluster_cluster_count < other.track_cluster_cluster_count

    def __le__(self, other):
        return self.track_cluster_cluster_count <= other.track_cluster_cluster_count

    def __eq__(self, other):
        return self.track_cluster_cluster_count == other.track_cluster_cluster_count

    def __ne__(self, other):
        return self.track_cluster_cluster_count != other.track_cluster_cluster_count

    def __gt__(self, other):
        return self.track_cluster_cluster_count > other.track_cluster_cluster_count

    def __ge__(self, other):
        return self.track_cluster_cluster_count >= other.track_cluster_cluster_count

    def __repr__(self) -> str:
        return f"TrackCluster(track_cluster_cluster_id={self.track_cluster_cluster_id}, track_cluster_cluster_count={self.track_cluster_cluster_count}, track_cluster_percent={self.track_cluster_percent})"


class Track:
    def __init__(self, track_id, track_count, track_cluster_list):
        self.track_id = track_id
        self.track_count = track_count
        self.track_cluster_list = track_cluster_list
        self.track_cluster_list.sort(reverse=True)
        self.final_cluster = -1

    def get_cluster_set(self):
        cluster_set = set()
        for track_cluster in self.track_cluster_list:
            cluster_set.add(cluster_set)

        return cluster_set

    def get_majority_forming_cluster_id(self):

        if self.track_count <= 20:
            max_cluster_count = 0
            max_cluster_id = -1
            for track_cluster in self.track_cluster_list:
                if track_cluster.track_cluster_cluster_count > max_cluster_count:
                    max_cluster_count = track_cluster.track_cluster_cluster_count
                    max_cluster_id = track_cluster.track_cluster_cluster_id

            return max_cluster_id

        for track_cluster in self.track_cluster_list:
            if track_cluster.track_cluster_percent >= 80:
                return track_cluster.track_cluster_cluster_id
            else:
                break

        combined_percent = 0
        cluster_list = []

        for track_cluster in self.track_cluster_list:
            combined_percent += track_cluster.track_cluster_percent
            cluster_list.append(track_cluster.track_cluster_cluster_id)
            if combined_percent >= 80:
                break

        return cluster_list

    def __repr__(self) -> str:
        return f"Track(track_id={self.track_id}, track_count={self.track_count}, track_cluster_list={self.track_cluster_list})"


class TrackList:
    def __init__(self, df):
        self.track_list = self.get_track_list(df)

    def get_final_clusters(self):

        final_cluster_dict = {}
        combine_dict = {}

        for track in self.track_list:
            final_cluster = track.get_majority_forming_cluster_id()
            final_cluster_dict[track.track_id] = final_cluster
            if type(final_cluster) == list:
                combine_dict[track.track_id] = final_cluster

        existing_sets_list: list[set] = []

        for track_id, cluster_list in combine_dict.items():
            cluster_set = set(cluster_list)

            if len(existing_sets_list) == 0:
                existing_sets_list.append(cluster_set)
                continue

            for existing_sets in existing_sets_list:
                if len(existing_sets.intersection(cluster_set)) > 0:
                    existing_sets.update(cluster_set)
                else:
                    existing_sets_list.append(cluster_set)

        # assign the first value of the set to all the values in the set
        final_combo_clusters = {}
        for cluster_set in existing_sets_list:
            if len(cluster_set) == 0:
                continue
            cluster_id = cluster_set.pop()
            final_combo_clusters[cluster_id] = cluster_id
            for cluster in cluster_set:
                final_combo_clusters[cluster] = cluster_id

        for track_id, cluster in final_cluster_dict.items():
            if type(cluster) == list:
                final_cluster_dict[track_id] = final_combo_clusters[cluster[0]]
            elif cluster in final_combo_clusters:
                final_cluster_dict[track_id] = final_combo_clusters[cluster]

        return final_cluster_dict

    def get_track(self, track_id):
        for track in self.track_list:
            if track.track_id == track_id:
                return track

    @staticmethod
    def get_track_list(df):

        df["TrackClusterClass"] = df.apply(
            lambda row: TrackCluster(
                track_cluster_cluster_id=row["Track_Cluster_Cluster_ID"],
                track_cluster_cluster_count=row["Track_Cluster_Cluster_Count"],
                track_cluster_percent=row["Track_Cluster_Percent"],
            ),
            axis=1,
        )

        df = (
            df.groupby("Track")
            .agg(
                {
                    "Track_Count": "first",
                    "TrackClusterClass": lambda x: list(x),
                }
            )
            .reset_index()
        )

        df["TrackClass"] = df.apply(
            lambda row: Track(
                track_id=row["Track"],
                track_count=row["Track_Count"],
                track_cluster_list=row["TrackClusterClass"],
            ),
            axis=1,
        )

        return df["TrackClass"].tolist()

    def __repr__(self) -> str:
        return f"TrackList(track_list_count={len(self.track_list)})"


def get_final_cluster_ids(final_df):

    temp_df = final_df[["Track", "Track_Cluster_Cluster_ID"]].copy()

    #     Get count of each track

    track_count_df = (
        pd.DataFrame(temp_df[["Track"]].value_counts())
        .sort_values("Track")
        .reset_index()
        .rename(columns={"count": "Track_Count"})
    )

    #     Get count of each cluster in each track

    track_cluster_count_df = (
        pd.DataFrame(temp_df[["Track", "Track_Cluster_Cluster_ID"]].value_counts())
        .reset_index()
        .rename(columns={"count": "Track_Cluster_Cluster_Count"})
        .sort_values(["Track", "Track_Cluster_Cluster_ID"])
        .reset_index(drop=True)
    )

    temp_df = temp_df.merge(track_count_df, on="Track")
    temp_df = temp_df.merge(track_cluster_count_df, on=["Track", "Track_Cluster_Cluster_ID"])

    temp_df = temp_df.drop_duplicates().reset_index(drop=True)

    #     Get percentage of track cluster count in total track count

    temp_df["Track_Cluster_Percent"] = temp_df.apply(
        lambda row: (row["Track_Cluster_Cluster_Count"] / row["Track_Count"]) * 100, axis=1
    )
    
    track_list = TrackList(temp_df)
    
    final_cluster_dict = track_list.get_final_clusters()
    
    temp_df["Final_Cluster"] = temp_df["Track"].apply(lambda x: int(final_cluster_dict.get(x, -1)))
    
    temp_df = temp_df.drop(columns=["TrackClusterClass"], axis=1)

    return temp_df

In [8]:
final_df_cents, track_centroids_df = get_subset(encoding_df)

In [9]:
final_df_cents

,Frame,Track,Score,S,X,Y,Encoding,SimpleClusters,EnhancedClusters,Track_Cluster_ID
0,2,0,2.22,224.648232,906.707703,474.191551,"[-0.051031678915023804, 0.0820079892873764, 0....",2,0,0
1,3,0,2.52,224.648232,906.707703,475.645676,"[-0.05130009725689888, 0.07784049212932587, 0....",2,0,0
2,4,0,2.80,224.648232,906.707703,476.826820,"[-0.06155857816338539, 0.08215416222810745, 0....",2,0,0
3,5,0,3.04,224.648232,906.707703,476.905502,"[-0.04346255958080292, 0.10632488131523132, 0....",2,0,0
4,6,0,3.16,224.648232,906.707703,476.905502,"[-0.0333511047065258, 0.11201924085617065, 0.0...",2,0,0
...,...,...,...,...,...,...,...,...,...,...
1159,1669,21,0.90,272.457382,930.917114,509.418205,"[-0.07299832254648209, 0.024822507053613663, 0...",1,0,0
1160,1670,21,0.52,273.492447,930.917114,510.397530,"[-0.08045308291912079, 0.02412343956530094, 0....",1,0,0
1161,1671,21,0.22,273.492447,930.917114,510.458221,"[-0.08456198126077652, 0.022204358130693436, 0...",1,0,0
1162,1672,21,0.14,273.492447,930.120972,510.458221,"[-0.07901183515787125, 0.02437211200594902, 0....",1,0,0
1163,1673,21,0.04,273.492447,930.120972,510.397530,"[-0.06118103861808777, 0.02324485033750534, 0....",1,0,0

In [61]:
new_classes = perform_clustering(list(track_centroids_df["Track_Cluster_Centroid"]), max_clusters=12)
track_centroids_df["Track_Cluster_Cluster_ID"] = new_classes
track_centroids_df

,Track,Track_Cluster_ID,Track_Cluster_Centroid,Track_Cluster_Cluster_ID
0,0,0,"[-0.10704685292310184, 0.06011241003870964, 0....",10
1,1,0,"[-0.17377947399328494, 0.08656178003755109, 0....",3
2,1,1,"[-0.06863380968570709, 0.029264468078811962, 0...",7
3,2,0,"[-0.08570898473262786, 0.05358734056353569, 0....",10
4,2,1,"[-0.03469390839745756, 0.051482012029737234, 0...",2
...,...,...,...,...
75,63,0,"[-0.15789725217554304, 0.14165891458590826, 0....",1
76,63,2,"[-0.13035152213914053, 0.068234794107931, 0.11...",1
77,63,1,"[-0.1416431894669166, 0.06696716294838832, 0.1...",1
78,65,1,"[-0.1788943037390709, 0.09812840571006139, 0.1...",1
79,65,0,"[-0.15971091389656067, 0.06355408703287442, 0....",1

In [62]:
final_df_cents = final_df_cents.merge(
    track_centroids_df[["Track", "Track_Cluster_ID", "Track_Cluster_Cluster_ID"]],
    on=["Track", "Track_Cluster_ID"])

In [63]:
final_df_cents["Track_Cluster_Cluster_ID"].value_counts()

Track_Cluster_Cluster_ID
4     733
3     399
1     350
2     233
10    229
0     205
5     153
6     149
11     59
7      44
9      38
8      25
Name: count, dtype: int64

In [70]:
_temp_df = get_final_cluster_ids(final_df_cents)
_temp_df.sort_values(by=["Final_Cluster", "Track"])

[{2.0, 3.0, 5.0, 10.0, 11.0}, {4.0, 7.0}, {4.0, 7.0}, {4.0, 7.0}, {0.0, 6.0}, {0.0, 6.0}, {0.0, 6.0}, {0.0, 6.0}, {3.0, 11.0}, {3.0, 11.0}, {3.0, 11.0}, {3.0, 11.0}, {3.0, 11.0}, {3.0, 11.0}, {3.0, 11.0}]

,Track,Track_Cluster_Cluster_ID,Track_Count,Track_Cluster_Cluster_Count,Track_Cluster_Percent,Final_Cluster
22,16,0,84,84,100.000000,0
25,20,0,17,10,58.823529,0
26,20,2,17,7,41.176471,0
28,24,0,49,49,100.000000,0
42,44,6,114,52,45.614035,0
43,44,0,114,62,54.385965,0
47,51,1,39,39,100.000000,1
52,55,1,141,141,100.000000,1
53,57,1,96,96,100.000000,1
57,63,1,62,62,100.000000,1
58,65,1,12,12,100.000000,1
0,0,10,90,90,100.000000,2
3,2,10,18,10,55.555556,2
4,2,2,18,8,44.444444,2
5,3,2,25,15,60.000000,2
6,3,10,25,10,40.000000,2
7,4,10,119,119,100.000000,2
8,5,5,40,40,100.000000,2
9,6,2,93,93,100.000000,2
10,7,5,42,9,21.428571,2
11,7,2,42,33,78.571429,2
12,8,2,39,39,100.000000,2
15,10,2,19,19,100.000000,2
16,11,5,30,14,46.666667,2
17,11,2,30,16,53.333333,2
18,12,5,111,66,59.459459,2
19,12,3,111,45,40.540541,2
45,49,2,7,3,42.857143,2
46,49,5,7,4,57.142857,2
1,1,3,32,29,90.625000,3
2,1,7,32,3,9.375000,3
13,9,3,141,121,85.815603,3
14,9,5,141,20,14.184397,3
48,52,3,181,181,100.000000,3
20,15,4,192,184,95.833333,4
21,15,7,192,8,4.166667,4
23,19,4,53,41,77.358491,4
24,19,7,53,12,22.641509,4
30,27,4,87,87,100.000000,4
31,28,4,10,10,100.000000,4
32,31,7,31,12,38.709677,4
33,31,4,31,19,61.290323,4
35,33,4,121,121,100.000000,4
36,35,4,24,15,62.500000,4
37,35,7,24,9,37.500000,4
38,36,4,102,102,100.000000,4
40,40,4,60,60,100.000000,4
41,43,4,94,94,100.000000,4
34,32,6,26,26,100.000000,6
39,37,6,31,31,100.000000,6
44,45,6,40,40,100.000000,6
27,22,8,4,4,100.000000,8
29,25,8,21,21,100.000000,8
49,53,9,2,2,100.000000,9
54,58,9,3,3,100.000000,9
56,61,9,33,33,100.000000,9
50,54,3,72,23,31.944444,11
51,54,11,72,49,68.055556,11
55,59,11,10,10,100.000000,11

In [52]:
encoding_df = encoding_df.merge(_temp_df[["Track", "Final_Cluster"]].drop_duplicates(), on="Track")
encoding_df

,Frame,Track,Score,S,X,Y,Encoding,Clusters,Final_Cluster
0,0,0,0.900,36.476614,297.162888,90.748936,"[-0.11543373763561249, 0.08555301278829575, 0....",4,4
1,1,0,1.025,36.476614,297.162888,90.808826,"[-0.11543373763561249, 0.08555301278829575, 0....",4,4
2,2,0,1.120,36.499027,297.335709,90.877142,"[-0.12249568104743958, 0.10854216665029526, 0....",4,4
3,3,0,1.240,36.707996,297.335709,90.909981,"[-0.11383970081806183, 0.10473571717739105, 0....",4,4
4,4,0,1.300,36.707996,297.581314,90.928844,"[-0.12663236260414124, 0.10784599930047989, 0....",4,4
...,...,...,...,...,...,...,...,...,...
1677,7419,68,0.120,24.705498,326.812332,113.277267,"[-0.09212890267372131, 0.07119353860616684, 0....",4,4
1678,7420,68,0.180,24.665962,328.202698,112.748276,"[-0.09382065385580063, 0.05741628259420395, 0....",4,4
1679,7421,68,0.180,24.665962,328.752304,112.709496,"[-0.09585478156805038, 0.06786153465509415, 0....",4,4
1680,7422,68,0.120,24.665962,330.117081,112.589043,"[-0.11552995443344116, 0.06896164268255234, 0....",4,4
1681,7423,68,0.040,24.459568,330.117081,111.965424,"[-0.08465144038200378, 0.04684824496507645, 0....",4,4

In [53]:
encoding_df.to_pickle("../../output/video_temp/2qQs3Y9OJX0_c_01/pywork/new_encoding_df.pckl")

In [51]:
_temp_df["Final_Cluster"].value_counts()

Final_Cluster
0    18
2     9
4     7
6     4
3     2
1     2
Name: count, dtype: int64